services:
  core:
    build:
      context: "./"
      dockerfile: docker/main/Dockerfile
    container_name: core
    profiles:
      - prod
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://informatics-db:5432/informatics
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
    volumes:
      - /home/informatics/prod/files:/files
      - /home/informatics/prod/logs/core:/logs
    networks:
      informatics:
        aliases:
          - core
  informatics-ui:
    profiles:
      - prod
    build:
      context: "./informatics-ui"
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/informatics/prod/ui:/app
    environment:
      REACT_APP_API_HOST: core
      REACT_APP_API_PORT: 8080
    networks:
      informatics:
        aliases:
          - ui
  informatics-db:
    image: postgres:latest
    container_name: db
    profiles:
      - prod
    ports:
      - 5432:5432
    volumes:
      - /home/informatics/prod/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      informatics:
        aliases:
          - db
networks:
  informatics:
    driver: bridge