version: '3.3'
services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: ""
      dockerfile: docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3306:3306"
  informatics:
    build:
      context: ""
      dockerfile: docker/main/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8787:8787"