services:
  core_dev:
    profiles:
      - dev
    build:
      context: "./"
      dockerfile: docker/main/Dockerfile
    volumes:
      - /home/informatics/dev/files:/files
      - /home/informatics/dev/logs/core:/logs
    ports:
      - "8787:8787"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/informatics
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
    networks:
      informatics_dev:
        aliases:
          - core
  db_dev:
    image: postgres:latest
    container_name: db_dev
    profiles:
      - dev
    volumes:
        - /home/informatics/dev/data:/var/lib/postgresql/data
        - ./custom-postgresql.conf:/etc/postgresql/postgresql.conf
        - /home/informatics/dev/logs/db:/logs
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6432:5432"
    networks:
      informatics_dev:
        aliases:
            - db
  ui-dev:
    profiles:
      - dev
    build:
      context: "./informatics-ui"
      dockerfile: Dockerfile_dev
    volumes:
      - ./informatics-ui:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_API_HOST: core
      REACT_APP_API_PORT: 8080
    networks:
      informatics_dev:
        aliases:
            - ui
networks:
  informatics_dev:
    driver: bridge


volumes:
  postgres-data:
