version: "3.9"

services:
  informatics:
    build:
      context: "./"
      dockerfile: docker/main/Dockerfile
    volumes:
      - /home/informatics/files:/files
      - /home/informatics/logs/core:/logs
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass
      SPRING_REDIS_HOST: redis

  informatics-db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: informatics
      POSTGRES_USER: root
      POSTGRES_PASSWORD: a9erjcdmnjcDDe3
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
