version: '3.3'
services:
  informatics:
    build:
      context: "./"
      dockerfile: docker/main/Dockerfile
    volumes:
      - ./informatics-system/target-informatics:/opt/app/target
    ports:
      - "8080:8080"
      - "8787:8787"