services:
  core:
    image: informatics/core:${VERSION}
    container_name: core
    profiles:
      - prod
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://informatics-db:5432/informatics
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
    volumes:
      - /home/informatics/prod/files:/files
      - /home/informatics/prod/logs/core:/logs
    networks:
      informatics:
        aliases:
          - core
  informatics-ui:
    profiles:
      - prod
    image: informatics/ui:${VERSION}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/informatics/prod/ui:/app
    environment:
      REACT_APP_API_HOST: core
      REACT_APP_API_PORT: 8080
    networks:
      informatics:
        aliases:
          - ui
  informatics-db:
    image: postgres:latest
    container_name: db
    profiles:
      - prod
    ports:
      - 5432:5432
    volumes:
      - /home/informatics/prod/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      informatics:
        aliases:
          - db
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    profiles:
      - prod
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9093,DOCKER://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9093,DOCKER://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      informatics:
        aliases:
          - kafka
  worker:
    depends_on:
      - kafka
    image: informatics/worker:${VERSION}
    profiles:
      - prod
    volumes:
      - /home/informatics/prod/files/tasks:/files
      - /home/informatics/prod/files/worker/shared:/shared
      - /home/informatics/prod/logs/worker:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8999:8989"
    environment:
      JDBC_URL: jdbc:postgresql://db:5432/informatics
      JDBC_USERNAME: ${DB_USER}
      JDBC_PASSWORD: ${DB_PASSWORD}
      APP_ID: 1
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      informatics:
        aliases:
          - worker
networks:
  informatics:
    driver: bridge